name: Post Results to PR

on:
  workflow_run:
    workflows: ["Validate Exercises"]
    types:
      - completed

jobs:
  post-results:
    runs-on: ubuntu-latest

    steps:
      - name: Get validation results
        id: get_validation_results
        run: |
          # Asignar valores predeterminados a las variables si no están definidas
          ERROR_FLAG=${{ github.event.workflow_run.outputs.error_flag || 0 }}
          ERROR_MESSAGES=${{ github.event.workflow_run.outputs.error_messages || '""' }}

          echo "ERROR_FLAG=$ERROR_FLAG"
          echo "ERROR_MESSAGES=$ERROR_MESSAGES"

          if [ "$ERROR_FLAG" -eq "1" ]; then
            # Publicar comentario de error en PR
            curl -X POST -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
              -d "{\"body\": \"❌ Errores encontrados en la validación del PR:\n$ERROR_MESSAGES\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          else
            # Publicar comentario de éxito en PR
            curl -X POST -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
              -d "{\"body\": \"✅ Validación completada sin errores.\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          fi

          # Exportar estado para el siguiente workflow
          echo "should_close=$ERROR_FLAG" >> $GITHUB_OUTPUT

      - name: Set output for should_close
        run: |
          echo "should_close=${{ steps.get_validation_results.outputs.should_close }}" >> $GITHUB_ENV
