name: Post Results to PR

on:
  workflow_run:
    workflows: ["PR Check"]
    types:
      - completed

jobs:
  post-results:
    runs-on: ubuntu-latest

    steps:
      - name: Get validation results
        id: get_validation_results
        run: |
          # Obtener los resultados del workflow anterior
          ERROR_FLAG=${{ github.event.workflow_run.outputs.error_flag || 0 }}
          ERROR_MESSAGES=${{ github.event.workflow_run.outputs.error_messages || '""' }}

          echo "ERROR_FLAG=$ERROR_FLAG"
          echo "ERROR_MESSAGES=$ERROR_MESSAGES"

          # Obtener el número del PR desde el entorno
          PR_NUMBER=${{ env.pr_number }}
          echo "PR_NUMBER=$PR_NUMBER"

          if [ "$ERROR_FLAG" -eq "1" ]; then
            # Publicar comentario de error en PR
            curl -X POST -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
              -d "{\"body\": \"❌ Errores encontrados en la validación del PR:\n$ERROR_MESSAGES\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
          else
            # Publicar comentario de éxito en PR
            curl -X POST -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
              -d "{\"body\": \"✅ Validación completada sin errores.\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
          fi

          # Exportar estado para el siguiente workflow
          echo "::set-output name=should_close::${ERROR_FLAG}"
