name: Validar Ejercicio

on:
  pull_request:
    paths:
      - "Selenium-exercises/**"

jobs:
  trigger-validator:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar workflow de validación en Validator
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
          -d '${{ github.head_ref }}' \
          https://api.github.com/repos/Akradeveloper/Validator/actions/workflows/validate.yml/dispatches
