name: Validar Ejercicio Completo

on:
  pull_request:
    # Este evento se dispara para cualquier PR en cualquier rama
    types: [opened, edited, synchronize, reopened] # Para que se ejecute cuando el PR se abra, edite o sincronice

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Paso para obtener el código del repositorio
      - name: Chequear el código
        uses: actions/checkout@v2
        with:
          repository: Akradeveloper/Selenium-exercises
          token: ${{ secrets.TOKEN_GITHUB }}
          ref: ${{ github.head_ref }} # La rama del PR

      # Verificar la estructura de directorios
      - name: Verificar la estructura de directorios
        run: |
          echo "Estructura de directorios:"
          ls -R ./  # Mostrar la estructura completa de directorios para depuración

      # Encontrar subcarpetas que contienen package.json o pom.xml
      - name: Encontrar subcarpetas de ejercicios
        run: |
          # Buscar las subcarpetas que contienen package.json o pom.xml
          EXERCISE_FOLDERS=$(find ./ -maxdepth 1 -type d \
            \( -exec test -e "{}/package.json" \; -o -exec test -e "{}/pom.xml" \; \) \
            -exec basename {} \;)

          # Mostrar las subcarpetas encontradas
          echo "Subcarpetas encontradas: $EXERCISE_FOLDERS"

          # Establecer la salida para usarla en pasos posteriores
          echo "folders=$EXERCISE_FOLDERS" >> $GITHUB_ENV

      # Validar cada subcarpeta de ejercicios con las verificaciones adicionales
      - name: Validar cada ejercicio
        run: |
          # Iterar sobre las carpetas encontradas
          for FOLDER in ${{ env.folders }}; do
            echo "Validando carpeta $FOLDER"
            
            # Comprobar si la subcarpeta tiene un directorio 'src'
            if [ ! -d "$FOLDER/src" ]; then
              echo "No se encontró el directorio 'src' en $FOLDER. Se omite esta carpeta."
              continue  # Si no existe src, se omite esta carpeta y se pasa a la siguiente
            fi
            
            # Si existe 'src', realizar las validaciones
            echo "Directorio 'src' encontrado en $FOLDER. Realizando comprobaciones adicionales..."

            # Verificar si la carpeta 'src/pages' existe
            if [ ! -d "$FOLDER/src/pages" ]; then
              echo "ERROR: Falta el directorio src/pages en $FOLDER"
              exit 1
            fi

            # Verificar si la carpeta 'src/tests' existe
            if [ ! -d "$FOLDER/src/tests" ]; then
              echo "ERROR: Falta el directorio src/tests en $FOLDER"
              exit 1
            fi

            # Verificar si el archivo .gitignore existe
            if [ ! -f "$FOLDER/.gitignore" ]; then
              echo "ERROR: Falta el archivo .gitignore en $FOLDER"
              exit 1
            fi

            # Verificar que no haya archivos de solución
            if find "$FOLDER" -type f -name "*solution*" | grep -q .; then
              echo "ERROR: No debe haber archivos de solución (e.g., solution.java) en $FOLDER"
              exit 1
            fi

            # Verificar que no haya archivos de test de ejemplo
            if find "$FOLDER" -type f -name "*test_example*" | grep -q .; then
              echo "ERROR: No debe haber archivos de test de ejemplo (e.g., test_example.js) en $FOLDER"
              exit 1
            fi

            # Comprobaciones de comentarios en el código
            if ! grep -r "/\*.*\*/" "$FOLDER/src" >/dev/null 2>&1; then
              echo "WARNING: No se encontraron comentarios de clase en el código de $FOLDER"
            fi
            if ! grep -r "//.*" "$FOLDER/src" >/dev/null 2>&1; then
              echo "WARNING: No se encontraron comentarios de métodos en el código de $FOLDER"
            fi

            # Validación de dependencias de Selenium en pom.xml (para proyectos Java)
            if [ -f "$FOLDER/pom.xml" ] && ! grep -q "selenium-java" "$FOLDER/pom.xml"; then
              echo "ERROR: Selenium no está listado como dependencia en pom.xml en $FOLDER"
              exit 1
            fi

            # Validación de dependencias de Selenium en package.json (para proyectos JavaScript)
            if [ -f "$FOLDER/package.json" ] && ! grep -q "selenium-webdriver" "$FOLDER/package.json"; then
              echo "ERROR: selenium-webdriver no está listado como dependencia en package.json en $FOLDER"
              exit 1
            fi

            # Buscar código comentado en todo el proyecto
            if grep -r "/\*.*" "$FOLDER" | grep -q .; then
              echo "ERROR: El código no debe estar comentado en el repositorio de $FOLDER"
              exit 1
            fi

            # Ejecutar ESLint si existe package.json (para proyectos JavaScript)
            if [ -f "$FOLDER/package.json" ]; then
              echo "Instalando dependencias de JavaScript en $FOLDER..."
              npm install --prefix "$FOLDER"
              echo "Ejecutando ESLint en $FOLDER..."
              npx eslint "$FOLDER/src/" || exit 1
            fi

            # Ejecutar Checkstyle si existe pom.xml (para proyectos Java)
            if [ -f "$FOLDER/pom.xml" ]; then
              echo "Instalando dependencias de Java en $FOLDER..."
              mvn install -f "$FOLDER/pom.xml"
              echo "Ejecutando Checkstyle en $FOLDER..."
              mvn checkstyle:check -f "$FOLDER/pom.xml" || exit 1
            fi
          done
