name: Validar Ejercicio Completo

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Chequear el código
        uses: actions/checkout@v2
        with:
          repository: Akradeveloper/Selenium-exercises
          token: ${{ secrets.TOKEN_GITHUB }}
          ref: ${{ github.head_ref }}

      # Parse PR description to find marked exercises and language
      - name: Analizar descripción del PR
        id: parse_pr_description
        run: |
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"

          # Detect language
          if echo "$PR_DESCRIPTION" | grep -q '\- \[X\] Java'; then
            echo "language=java" >> $GITHUB_ENV
          elif echo "$PR_DESCRIPTION" | grep -q '\- \[X\] JavaScript'; then
            echo "language=javascript" >> $GITHUB_ENV
          else
            echo "ERROR: No se especificó el lenguaje de programación o más de uno fue marcado."
            exit 1
          fi

          # Detect exercises
          EXERCISES=""
          for i in {1..3}; do
            if echo "$PR_DESCRIPTION" | grep -q "\- \[X\] Ejercicio $i"; then
              EXERCISES="$EXERCISES $i"
            fi
          done
          if [ -z "$EXERCISES" ]; then
            echo "ERROR: No se marcaron ejercicios para validar."
            exit 1
          fi
          echo "marked_exercises=$EXERCISES" >> $GITHUB_ENV

      # Validate based on marked exercises and language
      - name: Validar ejercicios seleccionados
        run: |
          for EXERCISE in ${{ env.marked_exercises }}; do
            FOLDER="./ejercicio-$EXERCISE"
            
            echo "Validando $FOLDER... con ${{ env.language }}"
            
            # Java validation for Ejercicio 1
            if [[ $EXERCISE == "1" && "${{ env.language }}" == "java" ]]; then
               if [ ! -d "$FOLDER/src/pages" ]; then
              echo "ERROR: Falta el directorio src/pages en $FOLDER"
              ERROR_FLAG=1
            fi

            # Verificar si la carpeta 'src/tests' existe
            if [ ! -d "$FOLDER/src/tests" ]; then
              echo "ERROR: Falta el directorio src/tests en $FOLDER"
              ERROR_FLAG=1
            fi

            # Verificar si el archivo .gitignore existe
            if [ ! -f "$FOLDER/.gitignore" ]; then
              echo "ERROR: Falta el archivo .gitignore en $FOLDER"
              ERROR_FLAG=1
            fi

            # Verificar que no haya archivos de solución
            if find "$FOLDER" -type f -name "*solution*" | grep -q .; then
              echo "ERROR: No debe haber archivos de solución (e.g., solution.java) en $FOLDER"
              ERROR_FLAG=1
            fi

            # Verificar que no haya archivos de test de ejemplo
            if find "$FOLDER" -type f -name "*test_example*" | grep -q .; then
              echo "ERROR: No debe haber archivos de test de ejemplo (e.g., test_example.js) en $FOLDER"
              ERROR_FLAG=1
            fi

            # Comprobaciones de comentarios en el código
            if ! grep -r "/\*.*\*/" "$FOLDER/src" >/dev/null 2>&1; then
              echo "WARNING: No se encontraron comentarios de clase en el código de $FOLDER"
            fi
            if ! grep -r "//.*" "$FOLDER/src" >/dev/null 2>&1; then
              echo "WARNING: No se encontraron comentarios de métodos en el código de $FOLDER"
            fi
            if [ ! -f "$FOLDER/pom.xml" ]; then
                echo "ERROR: Falta el archivo pom.xml en $FOLDER"
                ERROR_FLAG=1
            fi
            if ! grep -q "selenium-java" "$FOLDER/pom.xml"; then
                echo "ERROR: Falta la dependencia de selenium-java en $FOLDER/pom.xml"
                ERROR_FLAG=1
            fi
              # Verificar si 'pages' y 'tests' existen
            if [ ! -d "$FOLDER/src/pages" ]; then
                echo "ERROR: Falta el directorio src/pages en $FOLDER"
                ERROR_FLAG=1
            fi
            if [ ! -d "$FOLDER/src/tests" ]; then
                echo "ERROR: Falta el directorio src/tests en $FOLDER"
                ERROR_FLAG=1
            fi
              # Ejecutar Checkstyle si pom.xml existe
              mvn -f "$FOLDER/pom.xml" checkstyle:check || ERROR_FLAG=1

            
            # JavaScript validation for Ejercicio 1
            if [[ $EXERCISE == "1" && "${{ env.language }}" == "javascript" ]]; then
              if [ ! -f "$FOLDER/package.json" ]; then
                echo "ERROR: Falta el archivo package.json en $FOLDER"
                ERROR_FLAG=1
              fi
              if ! grep -q "selenium-webdriver" "$FOLDER/package.json"; then
                echo "ERROR: Falta la dependencia selenium-webdriver en $FOLDER/package.json"
                ERROR_FLAG=1
              fi
              # Verificar si 'pages' y 'tests' existen
              if [ ! -d "$FOLDER/src/pages" ]; then
                echo "ERROR: Falta el directorio src/pages en $FOLDER"
                ERROR_FLAG=1
              fi
              if [ ! -d "$FOLDER/src/tests" ]; then
                echo "ERROR: Falta el directorio src/tests en $FOLDER"
                ERROR_FLAG=1
              fi
              # Ejecutar ESLint si package.json existe
              npm install --prefix "$FOLDER"
              npx eslint "$FOLDER/src/" || ERROR_FLAG=1
            fi      
            # Additional validations can be added for other exercises here
          done
            if [ $ERROR_FLAG -eq 1 ]; then
            exit 1
            fi
