name: Validar Ejercicio Completo

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear el código
        uses: actions/checkout@v2
        with:
          repository: Akradeveloper/Selenium-exercises
          token: ${{ secrets.TOKEN_GITHUB }}
          ref: ${{ github.head_ref }}

      # Parse PR description to find marked exercises and language
      - name: Analizar descripción del PR
        id: parse_pr_description
        run: |
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"

          # Detect language
          if echo "$PR_DESCRIPTION" | grep -q '\- \[X\] Java'; then
            echo "language=java" >> $GITHUB_ENV
          elif echo "$PR_DESCRIPTION" | grep -q '\- \[X\] JavaScript'; then
            echo "language=javascript" >> $GITHUB_ENV
          else
            echo "ERROR: No se especificó el lenguaje de programación o más de uno fue marcado."
            exit 1
          fi

          # Detect exercises
          EXERCISES=""
          for i in {1..3}; do
            if echo "$PR_DESCRIPTION" | grep -q "\- \[X\] Ejercicio $i"; then
              EXERCISES="$EXERCISES $i"
            fi
          done
          if [ -z "$EXERCISES" ]; then
            echo "ERROR: No se marcaron ejercicios para validar."
            exit 1
          fi
          echo "marked_exercises=$EXERCISES" >> $GITHUB_ENV

      # Validate based on marked exercises and language
      - name: Validar ejercicios seleccionados
        id: validate_exercises
        run: |
          ERROR_FLAG=0  # Initialize the flag at the start
          ERROR_MESSAGES=""  # Store all error messages to post them later
          for EXERCISE in ${{ env.marked_exercises }}; do
            FOLDER="./ejercicio-$EXERCISE"
            
            echo "Validando $FOLDER... con ${{ env.language }}"
            
            # Java validation for Ejercicio 1
            if [[ $EXERCISE == "1" && "${{ env.language }}" == "java" ]]; then
              ERROR_FLAG_EXERCISE=0

              if [ ! -d "$FOLDER/src/pages" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/pages en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if [ ! -d "$FOLDER/src/tests" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/tests en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if [ ! -f "$FOLDER/.gitignore" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el archivo .gitignore en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if find "$FOLDER" -type f -name "*solution*" | grep -q .; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: No debe haber archivos de solución (e.g., solution.java) en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if find "$FOLDER" -type f -name "*test_example*" | grep -q .; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: No debe haber archivos de test de ejemplo (e.g., test_example.js) en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if ! grep -r "/\*.*\*/" "$FOLDER/src" >/dev/null 2>&1; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nWARNING: No se encontraron comentarios de clase en el código de $FOLDER"
              fi

              if ! grep -r "//.*" "$FOLDER/src" >/dev/null 2>&1; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nWARNING: No se encontraron comentarios de métodos en el código de $FOLDER"
              fi

              if [ ! -f "$FOLDER/pom.xml" ]; then
                  ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el archivo pom.xml en $FOLDER"
                  ERROR_FLAG_EXERCISE=1
              fi

              if ! grep -q "selenium-java" "$FOLDER/pom.xml"; then
                  ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta la dependencia de selenium-java en $FOLDER/pom.xml"
                  ERROR_FLAG_EXERCISE=1
              fi
              mvn -f "$FOLDER/pom.xml" checkstyle:check || ERROR_FLAG_EXERCISE=1

              if [ $ERROR_FLAG_EXERCISE -eq 1 ]; then
                ERROR_FLAG=1
              fi
            fi
            
            # JavaScript validation for Ejercicio 1
            if [[ $EXERCISE == "1" && "${{ env.language }}" == "javascript" ]]; then
              ERROR_FLAG_EXERCISE=0

              if [ ! -f "$FOLDER/package.json" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el archivo package.json en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if ! grep -q "selenium-webdriver" "$FOLDER/package.json"; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta la dependencia selenium-webdriver en $FOLDER/package.json"
                ERROR_FLAG_EXERCISE=1
              fi

              if [ ! -d "$FOLDER/src/pages" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/pages en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if [ ! -d "$FOLDER/src/tests" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/tests en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              npm install --prefix "$FOLDER"
              npx eslint "$FOLDER/src/" || ERROR_FLAG_EXERCISE=1

              if [ $ERROR_FLAG_EXERCISE -eq 1 ]; then
                ERROR_FLAG=1
              fi
            fi

            # Validation for Ejercicio 2
            if [[ $EXERCISE == "2" && "${{ env.language }}" == "java" ]]; then
              ERROR_FLAG_EXERCISE=0

              # Verificar que los directorios src/pages y src/tests existan
              if [ ! -d "$FOLDER/src/pages" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/pages en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if [ ! -d "$FOLDER/src/tests" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/tests en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              # Verificar la existencia del archivo .gitignore
              if [ ! -f "$FOLDER/.gitignore" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el archivo .gitignore en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              # Verificar la presencia de archivos de solución
              if find "$FOLDER" -type f -name "*solution*" | grep -q .; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: No debe haber archivos de solución (e.g., solution.java) en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              # Verificar la existencia del test
              if [ ! -f "$FOLDER/src/tests/form-test.java" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el archivo de test src/tests/form-test.java"
                ERROR_FLAG_EXERCISE=1
              fi

              # Validación adicional: revisar la lógica para enviar el formulario (dependiendo de la implementación)
              if ! grep -q "form.submit()" "$FOLDER/src/tests/form-test.java"; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: No se encontró la lógica para enviar el formulario en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              # Si se encontraron errores, actualizar el estado
              if [ $ERROR_FLAG_EXERCISE -eq 1 ]; then
                ERROR_FLAG=1
              fi
            fi

            # JavaScript validation for Ejercicio 2
            if [[ $EXERCISE == "2" && "${{ env.language }}" == "javascript" ]]; then
              ERROR_FLAG_EXERCISE=0

              if [ ! -f "$FOLDER/package.json" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el archivo package.json en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if ! grep -q "selenium-webdriver" "$FOLDER/package.json"; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta la dependencia selenium-webdriver en $FOLDER/package.json"
                ERROR_FLAG_EXERCISE=1
              fi

              if [ ! -d "$FOLDER/src/pages" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/pages en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if [ ! -d "$FOLDER/src/tests" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/tests en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              # Verificar que el archivo de test exista y esté bien configurado
              if [ ! -f "$FOLDER/src/tests/form-test.js" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el archivo de test src/tests/form-test.js"
                ERROR_FLAG_EXERCISE=1
              fi

              if ! grep -q "form.submit()" "$FOLDER/src/tests/form-test.js"; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: No se encontró la lógica para enviar el formulario en el test"
                ERROR_FLAG_EXERCISE=1
              fi

              npm install --prefix "$FOLDER"
              npx eslint "$FOLDER/src/" || ERROR_FLAG_EXERCISE=1

              if [ $ERROR_FLAG_EXERCISE -eq 1 ]; then
                ERROR_FLAG=1
              fi
            fi

            # Validation for Ejercicio 3
            if [[ $EXERCISE == "3" && "${{ env.language }}" == "java" ]]; then
              ERROR_FLAG_EXERCISE=0

              # Verificar que los directorios src/pages y src/tests existan
              if [ ! -d "$FOLDER/src/pages" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/pages en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if [ ! -d "$FOLDER/src/tests" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/tests en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              # Verificar la existencia del archivo .gitignore
              if [ ! -f "$FOLDER/.gitignore" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el archivo .gitignore en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              # Verificar la presencia de archivos de solución
              if find "$FOLDER" -type f -name "*solution*" | grep -q .; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: No debe haber archivos de solución (e.g., solution.java) en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              # Verificar la existencia del test
              if [ ! -f "$FOLDER/src/tests/form-test.java" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el archivo de test src/tests/form-test.java"
                ERROR_FLAG_EXERCISE=1
              fi

              # Validación adicional: revisar la lógica para enviar el formulario (dependiendo de la implementación)
              if ! grep -q "form.submit()" "$FOLDER/src/tests/form-test.java"; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: No se encontró la lógica para enviar el formulario en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi
              if [[ $EXERCISE == "3" && "${{ env.language }}" == "java" ]]; then
            ERROR_FLAG_EXERCISE=0

            # Assert 1: Comprobar que el enlace es clickeable
            LINK_TEXT="Ir a la siguiente página"
            if [ ! $(driver.findElements(By.linkText("$LINK_TEXT"))) ]; then
              ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: El enlace '$LINK_TEXT' no está disponible para hacer clic en Ejercicio 3"
              ERROR_FLAG_EXERCISE=1
            fi

            # Hacer clic en el enlace
            driver.findElement(By.linkText("$LINK_TEXT")).click();

            # Assert 2: Verificar que la URL cambió correctamente
            CURRENT_URL=$(driver.getCurrentUrl())
            if [[ ! "$CURRENT_URL" =~ "pagina-destino" ]]; then
              ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: La URL no cambió correctamente, URL actual: $CURRENT_URL"
              ERROR_FLAG_EXERCISE=1
            fi

            # Assert 3: Verificar que el elemento específico está visible en la página destino
            if [ ! $(driver.findElements(By.id("titulo-pagina-destino"))) ]; then
              ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: El elemento 'titulo-pagina-destino' no está visible en la página de destino"
              ERROR_FLAG_EXERCISE=1
            fi

            # Actualizar el indicador de errores si hay problemas
            if [ $ERROR_FLAG_EXERCISE -eq 1 ]; then
              ERROR_FLAG=1
            fi
          fi
              # Si se encontraron errores, actualizar el estado
              if [ $ERROR_FLAG_EXERCISE -eq 1 ]; then
                ERROR_FLAG=1
              fi
            fi

            # JavaScript validation for Ejercicio 3
            if [[ $EXERCISE == "3" && "${{ env.language }}" == "javascript" ]]; then
              ERROR_FLAG_EXERCISE=0

              if [ ! -f "$FOLDER/package.json" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el archivo package.json en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if ! grep -q "selenium-webdriver" "$FOLDER/package.json"; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta la dependencia selenium-webdriver en $FOLDER/package.json"
                ERROR_FLAG_EXERCISE=1
              fi

              if [ ! -d "$FOLDER/src/pages" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/pages en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              if [ ! -d "$FOLDER/src/tests" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el directorio src/tests en $FOLDER"
                ERROR_FLAG_EXERCISE=1
              fi

              # Verificar que el archivo de test exista y esté bien configurado
              if [ ! -f "$FOLDER/src/tests/form-test.js" ]; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: Falta el archivo de test src/tests/form-test.js"
                ERROR_FLAG_EXERCISE=1
              fi

              if ! grep -q "form.submit()" "$FOLDER/src/tests/form-test.js"; then
                ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: No se encontró la lógica para enviar el formulario en el test"
                ERROR_FLAG_EXERCISE=1
              fi
               // Assert 1: Comprobar que el enlace es clickeable
            const link = await driver.findElement(By.linkText('Ir a la siguiente página'));
            if (!link) {
              ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: El enlace 'Ir a la siguiente página' no está disponible para hacer clic en Ejercicio 3";
              ERROR_FLAG_EXERCISE = 1;
            }

            // Hacer clic en el enlace
            await link.click();

            // Assert 2: Verificar que la URL cambió correctamente
            const currentUrl = await driver.getCurrentUrl();
            if (!currentUrl.includes("pagina-destino")) {
              ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: La URL no cambió correctamente, URL actual: ${currentUrl}";
              ERROR_FLAG_EXERCISE = 1;
            }

            // Assert 3: Verificar que el elemento específico está visible en la página destino
            const element = await driver.findElement(By.id('titulo-pagina-destino'));
            if (!(await element.isDisplayed())) {
              ERROR_MESSAGES="$ERROR_MESSAGES\nERROR: El elemento 'titulo-pagina-destino' no está visible en la página de destino";
              ERROR_FLAG_EXERCISE = 1;
            }

            // Actualizar el indicador de errores si hay problemas
            if (ERROR_FLAG_EXERCISE === 1) {
              ERROR_FLAG = 1;
            }
          fi

              npm install --prefix "$FOLDER"
              npx eslint "$FOLDER/src/" || ERROR_FLAG_EXERCISE=1

              if [ $ERROR_FLAG_EXERCISE -eq 1 ]; then
                ERROR_FLAG=1
              fi
            fi


          done

          if [ $ERROR_FLAG -eq 1 ]; then
            echo -e "Errores encontrados durante la validación:\n$ERROR_MESSAGES"
            curl -X POST -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
              -d "{\"body\": \"Errores encontrados en la validación del PR:\n$ERROR_MESSAGES\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
            exit 1
          fi

      # Close the PR if there are validation errors
      - name: Cerrar PR si hay errores
        if: failure()
        uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.TOKEN_GITHUB }}
          comment: Auto-closing pull request
          delete-branch: false
