name: Validar Ejercicio

on:
  pull_request:
    paths:
      - "Selenium-exercises/**" # Detecta cambios en cualquier archivo dentro de 'Selenium-exercises'

  workflow_dispatch: # Permite ejecutar manualmente el workflow

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener el código del repositorio
      - name: Obtener código del repositorio de ejercicios
        uses: actions/checkout@v2
        with:
          repository: Akradeveloper/Selenium-exercises # Reemplaza con tu repositorio
          token: ${{ secrets.TOKEN_GITHUB }} # Usa el token secreto
          ref: ${{ github.head_ref }} # La rama del PR

      # Encontrar las subcarpetas de ejercicios
      - name: Encontrar subcarpetas de ejercicios
        id: find_exercises
        run: |
   
      # Buscar las subcarpetas de ejercicios que contienen package.json o pom.xml
          EXERCISE_FOLDERS=$(find ./* -maxdepth 1 -type d \
      \( -exec test -e "{}/package.json" \; -o -exec test -e "{}/pom.xml" \; \) \
      -exec basename {} \;)

    echo "Subcarpetas encontradas: $EXERCISE_FOLDERS"
    echo "::set-output name=folders::$EXERCISE_FOLDERS"

      # Paso 3: Validar cada subcarpeta de ejercicios
      - name: Validar cada ejercicio
        run: |
          for FOLDER in ${{ steps.find_exercises.outputs.folders }}; do
            echo "Validando carpeta $FOLDER"

            # Validación de estructura de directorios y archivos
            if [ ! -d "$FOLDER/src/pages" ]; then
              echo "ERROR: Falta el directorio src/pages en $FOLDER"
              exit 1
            fi
            if [ ! -d "$FOLDER/src/tests" ]; then
              echo "ERROR: Falta el directorio src/tests en $FOLDER"
              exit 1
            fi
            if [ ! -f "$FOLDER/.gitignore" ]; then
              echo "ERROR: Falta el archivo .gitignore en $FOLDER"
              exit 1
            fi

            # Verificar archivos no permitidos
            if find "$FOLDER" -type f -name "*solution*" | grep -q .; then
              echo "ERROR: No debe haber archivos de solución (e.g., solution.java) en $FOLDER"
              exit 1
            fi
            if find "$FOLDER" -type f -name "*test_example*" | grep -q .; then
              echo "ERROR: No debe haber archivos de test de ejemplo (e.g., test_example.js) en $FOLDER"
              exit 1
            fi

            # Comprobaciones de comentarios
            if ! grep -r "/\*.*\*/" "$FOLDER/src" >/dev/null 2>&1; then
              echo "WARNING: No se encontraron comentarios de clase en el código de $FOLDER"
            fi
            if ! grep -r "//.*" "$FOLDER/src" >/dev/null 2>&1; then
              echo "WARNING: No se encontraron comentarios de métodos en el código de $FOLDER"
            fi

            # Validación de dependencias de Selenium
            if [ -f "$FOLDER/pom.xml" ] && ! grep -q "selenium-java" "$FOLDER/pom.xml"; then
              echo "ERROR: Selenium no está listado como dependencia en pom.xml en $FOLDER"
              exit 1
            fi
            if [ -f "$FOLDER/package.json" ] && ! grep -q "selenium-webdriver" "$FOLDER/package.json"; then
              echo "ERROR: selenium-webdriver no está listado como dependencia en package.json en $FOLDER"
              exit 1
            fi

            # Buscar código comentado en todo el proyecto
            if grep -r "/\*.*" "$FOLDER" | grep -q .; then
              echo "ERROR: El código no debe estar comentado en el repositorio de $FOLDER"
              exit 1
            fi

            # Ejecución de ESLint si es un proyecto JavaScript
            if [ -f "$FOLDER/package.json" ]; then
              echo "Instalando dependencias de JavaScript en $FOLDER..."
              npm install --prefix "$FOLDER"
              echo "Ejecutando ESLint en $FOLDER..."
              npx eslint "$FOLDER/src/" || exit 1
            fi

            # Ejecución de Checkstyle si es un proyecto Java
            if [ -f "$FOLDER/pom.xml" ]; then
              echo "Instalando dependencias de Java en $FOLDER..."
              mvn install -f "$FOLDER/pom.xml"
              echo "Ejecutando Checkstyle en $FOLDER..."
              mvn checkstyle:check -f "$FOLDER/pom.xml" || exit 1
            fi
          done
