name: Validar Ejercicio

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear el código
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          ref: ${{ github.head_ref }}

      - name: Leer el contenido del PR para seleccionar ejercicio y lenguaje
        id: pr_content
        run: |
          PR_BODY=$(curl -s -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.body')
          echo "$PR_BODY" > pr_body.txt

          # Determinar el ejercicio y el lenguaje
          EXERCISE=0
          LANGUAGE=""

          if grep -q "\- \[x\] Ejercicio 1" pr_body.txt; then
            EXERCISE=1
          fi

          if grep -q "\- \[x\] Java\b" pr_body.txt; then
            LANGUAGE="Java"
          elif grep -q "\- \[x\] JavaScript\b" pr_body.txt; then
            LANGUAGE="JavaScript"
          fi

          echo "EXERCISE=$EXERCISE" >> $GITHUB_ENV
          echo "LANGUAGE=$LANGUAGE" >> $GITHUB_ENV

      - name: Validar Ejercicio 1 en Java
        if: env.EXERCISE == '1' && env.LANGUAGE == 'Java'
        run: |
          echo "Validando ejercicio 1 en Java"
          if [ ! -d "ejercicio-1/src/pages" ]; then
            echo "ERROR: Falta el directorio src/pages en ejercicio-1"
            exit 1
          fi
          if [ ! -d "ejercicio-1/src/tests" ]; then
            echo "ERROR: Falta el directorio src/tests en ejercicio-1"
            exit 1
          fi
          if [ ! -f "ejercicio-1/pom.xml" ]; then
            echo "ERROR: Falta pom.xml en ejercicio-1"
            exit 1
          elif ! grep -q "selenium-java" "ejercicio-1/pom.xml"; then
            echo "ERROR: Selenium no está listado como dependencia en pom.xml"
            exit 1
          fi
          mvn checkstyle:check -f "ejercicio-1/pom.xml" || exit 1

      - name: Validar Ejercicio 1 en JavaScript
        if: env.EXERCISE == '1' && env.LANGUAGE == 'JavaScript'
        run: |
          echo "Validando ejercicio 1 en JavaScript"
          if [ ! -d "ejercicio-1/src/pages" ]; then
            echo "ERROR: Falta el directorio src/pages en ejercicio-1"
            exit 1
          fi
          if [ ! -d "ejercicio-1/src/tests" ]; then
            echo "ERROR: Falta el directorio src/tests en ejercicio-1"
            exit 1
          fi
          if [ ! -f "ejercicio-1/package.json" ]; then
            echo "ERROR: Falta package.json en ejercicio-1"
            exit 1
          elif ! grep -q "selenium-webdriver" "ejercicio-1/package.json"; then
            echo "ERROR: selenium-webdriver no está listado como dependencia en package.json"
            exit 1
          fi
          npm install --prefix "ejercicio-1"
          npx eslint "ejercicio-1/src/" || exit 1
