name: Validar Ejercicio Completo

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear el código
        uses: actions/checkout@v2
        with:
          repository: Akradeveloper/Selenium-exercises
          token: ${{ secrets.TOKEN_GITHUB }}
          ref: ${{ github.head_ref }}
      - name: Verificar la existencia de get_pr_details.sh
        run: |
          ls -l ./scripts/
      - name: Forzar permisos de ejecución
        run: |
          chmod -R +x ./scripts
      - name: Obtener detalles del PR
        run: |
          chmod +x ./scripts/get_pr_details.sh
          ./scripts/get_pr_details.sh
          env:
            PR_BODY: ${{ github.event.pull_request.body }}
            PR_TITLE: ${{ github.event.pull_request.title }}
            PR_NUMBER: ${{ github.event.pull_request.number }}
      - name: Validar ejercicios seleccionados
        run: |
          ./scripts/validate_exercise.sh
      - name: Cerrar PR si hay errores
        run: |
          ./scripts/close_pr.sh
