name: Validar Ejercicio Completo

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear el código
        uses: actions/checkout@v2
        with:
          repository: Akradeveloper/Selenium-exercises
          token: ${{ secrets.TOKEN_GITHUB }}
          ref: ${{ github.head_ref }}
      - name: Forzar permisos de ejecución
        run: |
          chmod -R +x ./scripts
      - name: Obtener detalles del PR
        run: |
          ./scripts/get_pr_details.sh

      - name: Validar ejercicios seleccionados
        run: |
          ./scripts/validate_exercise.sh

      - name: Cerrar PR si hay errores
        run: |
          ./scripts/close_pr.sh
