name: Validar Ejercicio Completo

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Chequear el código
        uses: actions/checkout@v2
        with:
          repository: Akradeveloper/Selenium-exercises
          token: ${{ secrets.TOKEN_GITHUB }}
          ref: ${{ github.head_ref }}

      # Parse PR description to find marked exercises and language
      - name: Analizar descripción del PR
        id: parse_pr_description
        run: |
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"

          # Detect language
          if echo "$PR_DESCRIPTION" | grep -q '\- \[X\] Java'; then
            echo "language=java" >> $GITHUB_ENV
          elif echo "$PR_DESCRIPTION" | grep -q '\- \[X\] JavaScript'; then
            echo "language=javascript" >> $GITHUB_ENV
          else
            echo "ERROR: No se especificó el lenguaje de programación o más de uno fue marcado."
            exit 1
          fi

          # Detect exercises
          EXERCISES=""
          for i in {1..3}; do
            if echo "$PR_DESCRIPTION" | grep -q "\- \[X\] Ejercicio $i"; then
              EXERCISES="$EXERCISES $i"
            fi
          done
          if [ -z "$EXERCISES" ]; then
            echo "ERROR: No se marcaron ejercicios para validar."
            exit 1
          fi
          echo "marked_exercises=$EXERCISES" >> $GITHUB_ENV

      # Validate based on marked exercises and language
      - name: Validar ejercicios seleccionados
        run: |
          for EXERCISE in ${{ env.marked_exercises }}; do
            FOLDER="./ejercicio-$EXERCISE"
            
            echo "Validando $FOLDER..."
            
            # Java validation for Ejercicio 1
            if [[ $EXERCISE == "1" && "${{ env.language }}" == "java" ]]; then
              if [ ! -f "$FOLDER/pom.xml" ]; then
                echo "ERROR: Falta el archivo pom.xml en $FOLDER"
                exit 1
              fi
              if ! grep -q "selenium-java" "$FOLDER/pom.xml"; then
                echo "ERROR: Falta la dependencia de selenium-java en $FOLDER/pom.xml"
                exit 1
              fi
              mvn -f "$FOLDER/pom.xml" checkstyle:check || exit 1
            fi
            
            # JavaScript validation for Ejercicio 1
            if [[ $EXERCISE == "1" && "${{ env.language }}" == "javascript" ]]; then
              if [ ! -f "$FOLDER/package.json" ]; then
                echo "ERROR: Falta el archivo package.json en $FOLDER"
                exit 1
              fi
              if ! grep -q "selenium-webdriver" "$FOLDER/package.json"; then
                echo "ERROR: Falta la dependencia de selenium-webdriver en $FOLDER/package.json"
                exit 1
              fi
              npm install --prefix "$FOLDER"
              npx eslint "$FOLDER/src/" || exit 1
            fi
            
            # Additional validations can be added for other exercises here
          done
